
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author njara lucien
 */
public class Fournisseur extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
     Connecter connect = new Connecter();
     ResultSet Rs=null;
      Statement ps=null;
      String requete;
      DefaultTableModel model=new DefaultTableModel();
      DefaultTableModel nodel=new DefaultTableModel();
    public Fournisseur() {
        initComponents();
      
         model.addColumn("idFrns");
         model.addColumn("nomFrns");
         model.addColumn("preFrns");
         model.addColumn("adrFrns");
        
        
     
         nodel.addColumn("idCli");
         nodel.addColumn("nomCli");
         nodel.addColumn("preCli");
         nodel.addColumn("adrCli");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void afficher(){
      if(BoxFrns.isSelected()){
          try{
             model.setRowCount(0);
            ps=connect.obtenirConnection().createStatement();
            ResultSet Rs=ps.executeQuery("Select * from fournisseur");
            while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("idFrns").toString(),Rs.getString("nomFrns").toString(),Rs.getString("preFrns").toString(),
                Rs.getString("adrFrns").toString()});
            
            }
        }catch(Exception e){
            System.err.println(e);
        }
        tblFrns.setModel(model);
      }else if(BoxCli.isSelected()){
           try{
             nodel.setRowCount(0);
            ps=connect.obtenirConnection().createStatement();
            ResultSet Rs=ps.executeQuery("Select * from client");
            while(Rs.next()){
            nodel.addRow(new Object[]{Rs.getString("idCli").toString(),Rs.getString("nomCli").toString(),Rs.getString("preCli").toString(),
                Rs.getString("adrCli").toString()});
            
            }
        }catch(Exception e){
            System.err.println(e);
        }
        tblCli.setModel(nodel);
      }
        
    }
     
      private void deplace(int i){
        if(BoxFrns.isSelected()){
           try{
            txtid.setText(model.getValueAt(i,0).toString());
            txtnom.setText(model.getValueAt(i,1).toString());
            txtprenom.setText(model.getValueAt(i,2).toString());
            txtadresse.setText(model.getValueAt(i,3).toString());
           }catch(Exception e){System.err.println(e);
        JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
       }else if(BoxCli.isSelected()){
           try{
            txtid.setText(nodel.getValueAt(i,0).toString());
            txtnom.setText(nodel.getValueAt(i,1).toString());
            txtprenom.setText(nodel.getValueAt(i,2).toString());
            txtadresse.setText(nodel.getValueAt(i,3).toString());
           }catch(Exception e){System.err.println(e);
        JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
       }
      }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtadresse = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BoxFrns = new javax.swing.JCheckBox();
        BoxCli = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox();
        txtrecherche = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFrns = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCli = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("LISTE DES CLIENTS ET DES FOURNISSEURS");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 13, 14, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NOM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 51, 28, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PRENOM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 89, 52, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ADRESSE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 118, 57, 15);

        txtid.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(txtid);
        txtid.setBounds(90, 11, 146, 20);

        txtnom.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(txtnom);
        txtnom.setBounds(90, 49, 146, 20);

        txtprenom.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(txtprenom);
        txtprenom.setBounds(90, 87, 146, 20);

        txtadresse.setBackground(new java.awt.Color(204, 255, 204));
        txtadresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadresseActionPerformed(evt);
            }
        });
        jPanel1.add(txtadresse);
        txtadresse.setBounds(90, 113, 146, 20);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("CATEGORIE D'ENREGISTREMENT");

        BoxFrns.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        BoxFrns.setText("fournisseur");
        BoxFrns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxFrnsActionPerformed(evt);
            }
        });

        BoxCli.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        BoxCli.setText("client");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BoxFrns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoxCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxFrns)
                .addGap(18, 18, 18)
                .addComponent(BoxCli)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton1.setText("Ajoutter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Recherche");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id", "nom", "prenom", "adresse" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        txtrecherche.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtrecherche.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(64, 64, 64)
                        .addComponent(jButton4))
                    .addComponent(txtrecherche))
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        jLabel7.setText("FOURNISSEUR LIST");

        jLabel8.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        jLabel8.setText("CLIENT LIST");

        tblFrns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "PRENOM", "ADRESSE"
            }
        ));
        tblFrns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFrnsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFrns);

        tblCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "PRENOM", "ADRESSE"
            }
        ));
        tblCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCli);

        jButton6.setIcon(new javax.swing.ImageIcon("E:\\visual studio\\java\\GestionVenteChapeau\\icon\\Exit.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtadresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadresseActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String requete;        
// TODO add your handling code her
        if(BoxFrns.isSelected()){
            String idFrns=txtid.getText();
            String nomFrns=txtnom.getText();
            String preFrns=txtprenom.getText();
            String adrFrns=txtadresse.getText();
             requete="INSERT INTO FOURNISSEUR(idFrns,nomFrns,preFrns,adrFrns) values('"+idFrns+"','"+nomFrns+"','"+preFrns+"','"+adrFrns+"')";
        }
        else if(BoxCli.isSelected()){
            String idCli=txtid.getText();
            String nomCli=txtnom.getText();
            String preCli=txtprenom.getText();
            String adrCli=txtadresse.getText();
             requete="INSERT INTO CLIENT(idCli,nomCli,preCli,adrCli) values('"+idCli+"','"+nomCli+"','"+preCli+"','"+adrCli+"')";
        }else{
            JOptionPane.showMessageDialog(this, "Veuillez cocher sur FOURNISSEUR ou CLIENT");
        }
        
        
            
        try {
                ps=connect.obtenirConnection().createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(Fournisseur.class.getName()).log(Level.SEVERE, null, ex);
                //System.out.println(ex);
            }
        try {
            ps.executeUpdate(requete);
            afficher();
        } catch (SQLException ex) {
            Logger.getLogger(Fournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            //stm.executeUpdate(requete);
            txtid.setText("");
            txtnom.setText("");
            txtprenom.setText("");
            txtadresse.setText("");
            afficher();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BoxFrnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxFrnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxFrnsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            if (JOptionPane.showConfirmDialog (null, "voulez vous vraiment supprimer?"
            ,"supprimer ",JOptionPane.YES_NO_OPTION  )==JOptionPane.OK_OPTION)
                if(txtid.getText().length()!=0 ){
                    if(BoxFrns.isSelected()){
                        ps.executeUpdate("Delete from fournisseur where idFrns="+txtid.getText());
                    }
                    else if(BoxCli.isSelected()){
                        ps.executeUpdate("Delete from client where idCli="+txtid.getText()); 
                        
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Veuillez remplir le champ id!");
                }
        
        }catch(Exception e){ 
            JOptionPane.showMessageDialog(null, "erreur de supprimer \n"+e.getMessage());
        }
            txtid.setText("");
            txtnom.setText("");
            txtprenom.setText("");
            txtadresse.setText("");
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            if(JOptionPane.OK_OPTION==JOptionPane.showConfirmDialog(null,"confirmer la modification","modification",
                    JOptionPane.YES_NO_OPTION) )
            {
                if(BoxFrns.isSelected()){
                    ps.executeUpdate("UPDATE fournisseur SET idFrns='"+txtid.getText()+"',nomFrns='"+txtnom.getText()+"',preFrns='"+txtprenom.getText()+"',adrFrns='"+txtadresse.getText()+"' WHERE idFrns="+txtid.getText()  );
                    afficher();}
                else if(BoxCli.isSelected()){
                    ps.executeUpdate("UPDATE client SET idCli='"+txtid.getText()+"',nomCli='"+txtnom.getText()+"',preCli='"+txtprenom.getText()+"',adrCli='"+txtadresse.getText()+"' WHERE idCli="+txtid.getText()  );
                    afficher();
                }
            } 
              
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "erreur modifier!!!");
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       if(BoxFrns.isSelected()){
         try{
            model.setRowCount(0);
            ps=connect.obtenirConnection().createStatement();
            ResultSet Rs=ps.executeQuery("Select * from fournisseur");
            while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("idFrns"),Rs.getString("nomFrns"),Rs.getString("preFrns"),
                Rs.getString("adrFrns")});
            
            }
        }catch(Exception e){
            System.err.println(e);
        }
        tblFrns.setModel(model);
        afficher();
      }else if(BoxCli.isSelected()){
          try{
            nodel.setRowCount(0);
            ps=connect.obtenirConnection().createStatement();
            ResultSet Rs=ps.executeQuery("Select * from client");
            while(Rs.next()){
            nodel.addRow(new Object[]{Rs.getString("idCli"),Rs.getString("nomCli"),Rs.getString("preCli"),
                Rs.getString("adrCli")});
            
            }
        }catch(Exception e){
            System.err.println(e);
        }
        tblCli.setModel(model);
        afficher();
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(BoxFrns.isSelected()){
        try{
            model.setRowCount(0);
            { 
               if( jComboBox.getSelectedIndex() ==0){
                  Rs=ps.executeQuery("Select * from fournisseur WHERE idFrns='"+txtrecherche.getText()+"'");
               } 
                else if( jComboBox.getSelectedIndex() ==1){
                  Rs=ps.executeQuery("Select * from  fournisseur WHERE nomFrns='"+txtrecherche.getText()+"'");
               }
              else if( jComboBox.getSelectedIndex() ==2){
                  Rs=ps.executeQuery("Select * from fournisseur WHERE preFrns='"+txtrecherche.getText()+"'");
               }
              else if( jComboBox.getSelectedIndex() ==3){
                  Rs=ps.executeQuery("Select * from fournisseur WHERE adrFrns='"+txtrecherche.getText()+"'");
               }
              
            }while(Rs.next()){
                Object[]fournisseur={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getString(4)};
                model.addRow(fournisseur);
            }if(model.getRowCount()==0){JOptionPane.showMessageDialog(null, " il n'y a aucun fournisseur "); }
            else{
                int i=0;
                deplace (i);
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }else if(BoxCli.isSelected()){
            try{
            nodel.setRowCount(0);
            { 
               if( jComboBox.getSelectedIndex() ==0){
                  Rs=ps.executeQuery("Select * from client WHERE idCli='"+txtrecherche.getText()+"'");
               } 
                else if( jComboBox.getSelectedIndex() ==1){
                  Rs=ps.executeQuery("Select * from client WHERE nomCli='"+txtrecherche.getText()+"'");
               }
              else if( jComboBox.getSelectedIndex() ==2){
                  Rs=ps.executeQuery("Select * from client WHERE preCli='"+txtrecherche.getText()+"'");
               }
              else if( jComboBox.getSelectedIndex() ==3){
                  Rs=ps.executeQuery("Select * from client WHERE adrCli='"+txtrecherche.getText()+"'");
               }
              
            }while(Rs.next()){
                Object[]client={Rs.getInt(1),Rs.getString(2),Rs.getString(3)};
                nodel.addRow(client);
            }if(nodel.getRowCount()==0){JOptionPane.showMessageDialog(null, " il n'y a aucun client"); }
            else{
                int i=0;
                deplace (i);
            }
        
           }catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
           }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblFrnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFrnsMouseClicked
        // TODO add your handling code here:
        try{
           int i=tblFrns.getSelectedRow();deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tblFrnsMouseClicked

    private void tblCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCliMouseClicked
        // TODO add your handling code here:
        try{
           int i=tblCli.getSelectedRow();deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tblCliMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fournisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BoxCli;
    private javax.swing.JCheckBox BoxFrns;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCli;
    private javax.swing.JTable tblFrns;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrecherche;
    // End of variables declaration//GEN-END:variables
}
